In [1]:
import torch
import numpy as np

In [6]:
data = [[1,2],[3,4]]
n_data = np.array(data)
t_data = torch.tensor(data)
print(n_data)
print(t_data)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [7]:
t_data = torch.from_numpy(n_data)
print(t_data)

tensor([[1, 2],
        [3, 4]])


In [8]:
t_ones = torch.ones_like(t_data)
print(t_ones)
t_rand = torch.rand_like(t_data, dtype = torch.float)
print(t_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.0730, 0.5504],
        [0.7663, 0.4178]])


In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.9580, 0.0602, 0.1460],
        [0.6690, 0.1911, 0.2056]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
t1 = torch.rand(3,4)
print(t1)
print(t1.shape)
print(t1.dtype)
print(t1.device)

tensor([[0.1553, 0.3060, 0.1671, 0.9565],
        [0.4031, 0.3485, 0.2095, 0.0109],
        [0.0587, 0.2699, 0.2981, 0.4869]])
torch.Size([3, 4])
torch.float32
cpu


In [15]:
if torch.cuda.is_available():
  t1 = t1.to('cuda')
print(t1.device)

cpu


In [21]:
t2 = torch.ones(4,4)
t2[:,-1]

tensor([1., 1., 1., 1.])

In [23]:
t21 = torch.cat([t2,t2,t2,t2])
t21

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
print(t1)
y1 = t1 @ t1.T
print(y1)
y2 = torch.matmul(t1, t1.T)
print(y2)
y3 = torch.rand_like(y1)
torch.matmul(t1, t1.T, out = y3)
z1 = t1 * t1
print(z1)
z2 = torch.mul(t1, t1)
print(z2)
z3 = torch.rand_like(z1)
torch.mul(t1, t1, out = z3)

tensor([[0.1553, 0.3060, 0.1671, 0.9565],
        [0.4031, 0.3485, 0.2095, 0.0109],
        [0.0587, 0.2699, 0.2981, 0.4869]])
tensor([[1.0605, 0.2147, 0.6072],
        [0.2147, 0.3279, 0.1855],
        [0.6072, 0.1855, 0.4023]])
tensor([[1.0605, 0.2147, 0.6072],
        [0.2147, 0.3279, 0.1855],
        [0.6072, 0.1855, 0.4023]])
tensor([[2.4121e-02, 9.3637e-02, 2.7924e-02, 9.1482e-01],
        [1.6248e-01, 1.2145e-01, 4.3889e-02, 1.1847e-04],
        [3.4480e-03, 7.2841e-02, 8.8882e-02, 2.3708e-01]])
tensor([[2.4121e-02, 9.3637e-02, 2.7924e-02, 9.1482e-01],
        [1.6248e-01, 1.2145e-01, 4.3889e-02, 1.1847e-04],
        [3.4480e-03, 7.2841e-02, 8.8882e-02, 2.3708e-01]])


tensor([[2.4121e-02, 9.3637e-02, 2.7924e-02, 9.1482e-01],
        [1.6248e-01, 1.2145e-01, 4.3889e-02, 1.1847e-04],
        [3.4480e-03, 7.2841e-02, 8.8882e-02, 2.3708e-01]])

In [30]:
sum_t1 = t1.sum()
print(sum_t1)
t1_item = sum_t1.item()
print(t1_item, type(t1_item))

tensor(3.6705)
3.6704936027526855 <class 'float'>


In [31]:
print(t1)
t1.add_(5)
print(t1)

tensor([[0.1553, 0.3060, 0.1671, 0.9565],
        [0.4031, 0.3485, 0.2095, 0.0109],
        [0.0587, 0.2699, 0.2981, 0.4869]])
tensor([[5.1553, 5.3060, 5.1671, 5.9565],
        [5.4031, 5.3485, 5.2095, 5.0109],
        [5.0587, 5.2699, 5.2981, 5.4869]])
